### ISSUE TITLE
Why won't it summon my favorite pet?

### ISSUE THREAD

**Issue by trilobots** [tflo/PetWalker#13]
![image](https://github.com/user-attachments/assets/92d15e9e-a1f8-458b-bfde-60f6ebb83a2d)

I can't seem to force a certain pet to summon. I removed all pets from favorites both with and without character specific on, and it keeps summoning the previously saved pet instead.

I want the ethereal soul trader out, it *says* i have it as the favorite, and that it should be summoning my favorites, yet it keeps summoing unborn val'kyr...why? How do I fix this?

**Comment by tflo** [comment]
_I think_ you are misunderstanding how PetWalker works:

1. The main functionality is: Restore (re-summon) the user’s pet when it gets lost. (Whenever you summon a pet, PW saves it to the database, so he knows the “right” pet.)
2. The other, optional, thing is to summon (via timer or keybind) of a new random pet from a defined pool. This is completely separate from the Restore functionality.

So, if you want to have _one_ particular pet out all the time, there is no need to set it as your only favorite. Just summon the pet (the Soul-Trader) from the Pet Journal[^1] and make sure that the new-pet timer is disabled, i.e set to zero (`0`).
_The Restore functionality (1) should take care that your Soul-Trader is always out._

What you are experiencing is exactly the Restore functionality (1): PetWalker restores your last summoned pet, which probably was the Unborn Val'kyr. I does not summon your only “random” favorite pet (the Soul-Trader), because the timer is deactivated.

However, you can also manually summon a new random pet from your pool with your new-pet keybind (or `/pw n` in the console, if you have not set the keybind). In your case, it will then summon your Soul-Trader, since it is the only one in your pet pool (see “Eligible pets: 1” in the status text).

But as said, no need to set your favorites to exactly one pet. Just summon the Soul-Trader from the Pet Journal, and PW should take care of it. (And if the timer is off, it will never be replaced with another pet.)

[^1]: PetWalker will only remember pets that have been summoned from the Pet Journal, Rematch, OPie, or by PW itself, but not from an action bar button. However, the latter has been added recently and is still in beta ([currently 2.3.0-beta3](https://www.curseforge.com/wow/addons/petwalker/files/5773204), see also [issue #12]( https://github.com/tflo/PetWalker/issues/12))

**Comment by trilobots** [comment]
I thought that was how it worked, and what i did was summon my soul trader before I took off and landed later, and val'kyr popped back up. 

I'll play with it again tomorrow and see if things are working.

**Comment by tflo** [comment]
> and what i did was summon my soul trader before I took off and landed later, and val'kyr popped back up

This is definitely not supposed to happen.

How did you summon the Soul-Trader? As mentioned in the footnote above, prior to v2.3.0, PW did not save a pet that was summoned from an action bar button (as opposed to being summoned from the Pet Journal / Rematch via right-click).

**Comment by trilobots** [comment]
Aha okay i wasn't summoning it from the pet journal.

Thanks so much!

**Comment by tflo** [comment]
> Aha okay i wasn't summoning it from the pet journal.

OK, please try v2.30-beta3 then (link in my post above). It should now save a pet no matter how it was summoned.

I'll close this, as it seems to be the same as Issue #12 . I'll post any updates or news there.

**Comment by tflo** [comment]
PS: If you find any issues with v2.30-beta, please post them also in #12.
